language: go
go:
  - "1.9.7"
  - "1.10.4"
  - "1.11.1"

sudo: false

env:
  - GO111MODULE=on

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh

